# -*- coding: utf-8 -*-
"""
Created on Fri Mar  1 15:16:10 2019

@author: Jess
"""

#import this

#a = 952  
#b = 849
#print(a*a + b*b)


#mystring = "wuUpGzBXxs9X4aJ74T4oAdCitharacanthus05lpDl79jJG603EHLJZipNCQfs3dN6dr4ePhItxbDaWlpmWoNqEmfx6R4Ls0p9IEqtu7hfKDnj0X8f3Zsl5dignus2WhHmWddPISDpy7FomCi3fm0LZg88eWyFPz6Rv966UKwgEs8QV8jk0szzDnOGXNsbWtYONjz."
#print(mystring[22:35 +1])
#print(mystring[119:124 +1])

#prev=int()
#for i in range(4066+1, 8075+1, 2):
#    prev=prev+i
#print(prev)

#file = open("rosalind_ini5.txt", "r")
#mylist = file.readlines()
#length=len(mylist)+1
#for i in range(1, length, 2):
#    print(mylist[i])
    
#mydna="CAACCACACTTTTAAGGTTGTTTGGCACTCTCCGATTGATCGACCGTAAACGGTGAGACCGGACACTTTGGGTGTTTCACAAGGTATCGGAGCGCTGCAAAATACTAATGAGCCACCCTAGTGTTTTGATTGGACCACCATCCACGGGGACATTCAGATATGTGGGTGATCTCTGTGCGACGTAGTACGCGATGGAAGGCCGATAGTCGTTCTCTTTAGCCCTCAACCGACAGCGATGTCGCCGATGAATGTCAGTAGGCGCTTTCGGTGTAACCTACGAATTAGCCAGTACCTTCATAACTGCCGCGCCGCCGCTTCTGCTACTCAGGAAGTTTAGCCACCGTATCACATCCAGGGTGTTAACGCGGCTTAGCCGCTCCGCACTGTTTATTAGCTACGTGTGCGCTCCTTCTCTAGATAAACATCATAACAGGTTGTCAGCCGGATACATAGAACACGGACTTAACGAACGTCAGCCCAGACCCGGCATAATCCTTGCAGCTATCAGCGTACAGAGCTTCTATTTATATGATTTTTACATGGCAGCCAGATTACACCGTAATCTACTCAGTTAAGCCCTATTCTATAGTGAGCCACCAACGTGCTAGCCGGGTCGTCCGAACTAAGAAATCGAAGAGTATGGTTTCAGTTATGCGGCGAGAGTGTTTGCTACAAGTCATGTTCCGAGGGAGATAAATTCCAATAGTGCGGTTTCGACCCAGAACGAAGACCGTGGTCGGACGAATCTCCTTCCCGAGATGGTATACTTCCGAGCTTTATCAGACATGGCATCTAACGTTCGCTCCGCCGGCTCTCCCGACTACAAACCGATGAGCGTCTGTACCCGTATGCACGTCGAGG"
#dictionary={}
#for i in mydna:
#    if i in dictionary:
#        dictionary[i] +=1
#    else:
#        dictionary[i] = 1

#print(dictionary["A"], dictionary["C"], dictionary["G"], dictionary["T"])

#file = open("rosalind_rna.txt", "r")
#t = file.readline()
#print(t.replace("T", "U"))





             